version: "3"

services:
  strapi:
    container_name: strapi
    image: strapi-app11 #Localimage name
    # build: ast
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - APP_KEYS=toBeModified1,toBeModified2
      - API_TOKEN_SALT=tobemodified
      - ADMIN_JWT_SECRET=tobemodified
      - TRANSFER_TOKEN_SALT=tobemodified
      - JWT_SECRET=QYC7MIOykoSewCZ0jP+22A==
    ports:
      - 1337:1337
    volumes:
      - ./app:/srv/app
      - ./_docker_volumes/public/uploads:/opt/app/public/uploads
    depends_on:
      - db

  db:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
  postgres-data:
