import frAaeColaco from '~/assets/fr-aae-colaco.jpeg';

const religiousVocationsEng = [
	{
		imageUrl: frAaeColaco,
		name: 'Late| Rev| Fr| Joseph N Lobo',
		ward: 'Kowdoor A',
		dob: '06-12-1929',
		dod: '31-08-1917',
		congregation: 'Secular, Mangalore Diocese ',
		parents: 'Late| Marcel Lobo, Late| Magdaline DSouza​',
	},
	{
		imageUrl: frAaeColaco,
		name: 'Late| Br| Paul Lobo',
		ward: 'Kowdoor A',
		dob: '04-12-1915',
		dod: '24-11-1993',
		congregation: 'Jesuit Order',
		parents: 'Late| Baltazar Lobo, Late| Magdaline DSouza​',
	},
	{
		imageUrl: frAaeColaco,
		name: 'Late| Rev| Fr| Cyril Rasquinha',
		ward: 'Pompei B',
		dob: '22-07-1932',
		dod: '26-03-2003',
		congregation: 'Secular, Delhi Archdiocese ',
		parents: 'Late| Ignatius Rasquinha, Late| Coses Rodrigues',
	},
	{
		imageUrl: frAaeColaco,
		name: 'Late| Rev| Fr| Herbert Pinto',
		ward: 'Kowdoor A',
		dob: '05-04-1936',
		dod: '06-07-2007',
		congregation: 'Capuchin',
		parents:'Late| Trindad Pinto, Late| Brijit Saldanha',
	},
	{
		imageUrl: frAaeColaco,
		name: 'Late| Rev| Fr| Joseph Peter Tauro',
		ward: 'Kandar B',
		dob: '04-03-1939',
		dod: '08-02-2013',
		congregation: 'Secular, Mangalore Diocese ',
		parents: 'Late| Kashmir Tauro, Late| Igneshia Tauro​',
	},
	{
		imageUrl: frAaeColaco,
		name: 'Late| Rev| Fr| Gilbert Pinto',
		ward: 'Kowdoor A',
		dob: '06-09-1945',
		dod: '23-11-2015',
		congregation: 'Secular, Chikkamangalore Diocese ',
		parents: 'Late| Elias Pinto, Late| Juvanna Lucy Rodrigues',
	},
	{
		imageUrl: frAaeColaco,
		name: 'Late| Rev| Fr| Gregory DCunha',
		ward: 'Kowdoor B',
		dob: '25-05-1942',
		dod: '04-10-2020',
		congregation: 'Secular, Shivamogga Diocese ',
		parents: 'Late| Denis DCunha, Late| Mary DCunha',
	},
	{
		imageUrl: frAaeColaco,
		name: 'Late| Rev| Fr| Stany DCunha',
		ward: 'Kowdoor B',
		dob: '26-12-1946',
		dod: '05-08-2019',
		congregation: 'Secular, Karwar Diocese ',
		parents: 'Late| Denis DCunha, Late| Mary DCunha',
	},
	{
		imageUrl: frAaeColaco,
		name: 'Late| Sr| Angela Pinto',
		ward: 'Kowdoor A',
		dob: '23-10-1921',
		dod: '04-01-2005',
		parents: 'Late| Mariyan Pinto, Late| Magdaline Miranda',
	},
	{
		imageUrl: frAaeColaco,
		name: 'Late| Sr| Agnes Pinto',
		ward: 'Kowdoor A',
		dob: '12-07-1919',
		dod: '24-01-2017',
    congregation: 'Charity',
		parents: 'Late| Benjamin Pinto, Late| Miliyana Pinto',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Late| Sr| Agnes DCunha',
		ward: 'Kowdoor B',
		dob: '04-11-1918',
		dod: '13-11-1988',
    congregation: 'Charity',
		parents: 'Late| Martin DCunha, Late| Angela Fernandes',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Late| Sr| Emiliana ',
		ward: 'Kowdoor B',
    dob: '',
		dod: '',
    congregation: 'Apostalic Carmel',
		parents: 'Late| Bajil Rodrigues, Late| Benedicta Rodrigues',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Late| Sr| Marjari ',
		ward: 'Kowdoor A',
		dob: '18-07-1940',
		dod: '28-07-2019',
    congregation: 'Bethany',
		parents:'Late| Trindad Pinto, Late| Brijit Saldanha',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Late| Sr| Marijohn ',
		ward: 'Kowdoor A',
		dob: '04-03-1944',
		dod: '30-08-2020',
    congregation: 'Bethany',
		parents:'Late| Trindad Pinto, Late| Brijit Saldanha',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Late| Sr| Melvis ',
		ward: 'Kowdoor B',
		dob: '12-07-1942',
		dod: '02-09-2005',
    congregation: 'Bethany',
		parents:'Late| Anthony Menezes, Late| Florine DCunha',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Late| Sr| Regis ',
		ward: 'Kowdoor B',
		dob: '23-01-1945',
		dod: '27-05-2016',
    congregation: 'Bethany',
		parents:'Late| Anthony Menezes, Late| Florine DCunha',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Late| Sr| Terez Margarett ',
		ward: 'Kowdoor B',
		dob: '21-12-1950',
		dod: '08-11-1987',
    congregation: 'O.C.D.',
		parents:'Late| Vincent DCunha, Late| Delphin Rodrigues',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Late| Sr| A Femia ',
		ward: 'Pompei A',
    dob: '',
		dod: '',
    congregation: 'Apostalic Carmel',
		parents:'Late| Domingo Rodrigues, Late| Magdaline Rodrigues',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Late| Sr| Gilberta',
		ward: 'Pompei A',
    dob: '',
		dod: '',
    congregation: 'Apostalic Carmel',
		parents:'Late| Alexander Rodrigues, Late| Marta Rodrigues',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Late| Sr| Mary Baptista Peris',
		ward: 'Pompei B',
    dob: '02-04-1949',
		dod: '21-05-2019',
    congregation: `St Ann's Providence`,
		parents:'Late| Bernard Peris, Late| Alice Lobo',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Late| Sr| Maria Nunsiyeta',
		ward: 'Kandar B',
    dob: '',
		dod: '09-06-1921',
    congregation: 'Apostalic Carmel',
		parents:'Late| Francis Tauro, Late| Catherine Pinto',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Rev| Fr| John Baptist Mendonca',
		ward: 'Kandar A',
		dob: '',
		dod: '',
		congregation: 'Jesuit',
		parents: 'Late| Ruzar Mendonca, Late| Florine Mendonca',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Rev| Fr| Felix Bajil Moras',
		ward: 'Gurpur',
		dob: '',
		dod: '',
		congregation: 'Secular, Nagpur Diocese ',
		parents: 'Late| Pascal Moras, Late| Pascinha Saldanha',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Rev| Fr| Andrew Leo Moras',
		ward: 'Gurpur',
		dob: '',
		dod: '',
		congregation: 'Secular, Nagpur Diocese ',
		parents: 'Late| Pascal Moras, Late| Pascinha Saldanha',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Rev| Fr| John Peris',
		ward: 'Church',
		dob: '',
		dod: '',
		congregation: 'Secular, Lucknow Diocese ',
		parents: 'Mr Lawrence Peris, Mr Cecilia Coelho',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Rev| Fr| Victor Lobo',
		ward: 'Gurpur',
		dob: '',
		dod: '',
		congregation: 'Secular, Lucknow Diocese ',
		parents: 'Late| Pascal Lobo, Late| Alice DSouza',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Rev| Dr | Fr| Pius Phedelis Pinto',
		ward: 'Kowdoor A',
		dob: '',
		dod: '',
		congregation: 'Secular, Mangalore Diocese ',
		parents: 'Late| Lawrence Fredrik Pinto, Mrs Stella Lobo',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Rev| Fr| Ivan Mendonca',
		ward: 'Church',
		dob: '',
		dod: '',
		congregation: 'Jesuit',
		parents: 'Mr Aloysius Mendonca, Late| Julina Mendonca',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Rev| Fr| Melwyn Mendonca',
		ward: 'Kandaar A',
		dob: '',
		dod: '',
		congregation: 'Jesuit',
		parents: ' Late| Gabriel Mendonca, Mrs Celine Mendonca',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Rev| Dr | Richard Francis DSouza',
		ward: 'Gurpur',
		dob: '',
		dod: '',
		congregation: 'Carmelite',
		parents: 'Mr Mauris DSouza, Mrs Eliza Pinto',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Rev| Dr | Rudolph Raj Pinto',
		ward: 'Kowdoor B',
		dob: '',
		dod: '',
		congregation: 'Carmelite',
		parents: ' Late| George Pinto, Late| Jeevith Pinto',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Rev| Dr | Rohan Miranda',
		ward: 'Gurpur',
		dob: '',
		dod: '',
		congregation: 'Capuchin',
		parents: 'Late| Leo Miranda, Mrs Lucy Miranda',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Rev| Fr| Vincent Saldanha',
		ward: 'Gurpur',
		dob: '',
		dod: '',
		congregation: 'Secular, Mangalore Diocese',
		parents: 'Late| John Saldanha, Mrs Gertrude Saldanha',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Rev| Fr| Santosh Menezes',
		ward: 'Kandar A',
		dob: '',
		dod: '',
		congregation: 'Secular, Mangalore Diocese',
		parents: 'Late| Antony Francis Menezes, Late| Anna Maria Menezes',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Rev| Fr| Anil Fernandes',
		ward: 'Pompei A',
		dob: '',
		dod: '',
		congregation: 'S.V.D.',
		parents: 'Mr Mauris Fernandes, Mrs Christin Mendonca',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Rev| Fr| Stephan Arun Lobo',
		ward: 'Church',
		dob: '',
		dod: '',
		congregation: 'Capuchin',
		parents: 'Late| William Lobo, Mrs Carmin Lobo',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Rev| Fr| Prakash DCunha',
		ward: 'Monel',
		dob: '',
		dod: '',
		congregation: 'Carmelite',
		parents: 'Late| Egidor DCunha, Mrs Irene DCunha',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Rev| Fr| Roshan Pinto ',
		ward: 'Kowdoor A',
		dob: '',
		dod: '',
		congregation: 'Carmelite',
		parents: 'Mr Norbert Pinto, Mrs Celine DSouza',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Sr| Melwyn ',
		ward: 'Kowdoor A',
		dob: '',
		dod: '',
		congregation: 'Bethany',
		parents:'Late| Trindad Pinto, Late| Brijit Saldanha',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Sr| Fleviyan ',
		ward: 'Kowdoor A',
		dob: '',
		dod: '',
		congregation: 'Bethany',
		parents:'Late| Trindad Pinto, Late| Brijit Saldanha',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Sr| Eveline ',
		ward: 'Kowdoor A',
		dob: '',
		dod: '',
		congregation: 'Bethany',
		parents:'Late| Sebastian Miranda, Late| Cecilia Pereira',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Sr| Nimpha ',
		ward: 'Kowdoor B',
		dob: '',
		dod: '',
		congregation: 'Bethany',
		parents:'Late| Peter Rodrigues, Late| Anna Maria Rodrigues',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Sr| Blanch Pinto ',
		ward: 'Kowdoor A',
		dob: '',
		dod: '',
		congregation: 'Charity',
		parents:'Late| Mark Pinto, Late| Piyad Nazreth',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Sr| Norbetine ',
		ward: 'Kowdoor A',
		dob: '',
		dod: '',
		congregation: 'Bethany',
		parents:'Late| Mark Pinto, Late| Piyad Nazreth',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Sr| Feliciyan ',
		ward: 'Kowdoor A',
		dob: '',
		dod: '',
    congregation: 'Apostalic Carmel',
		parents:'Late| Jerome Pinto, Late| Juliana Nazreth',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Sr| Mericiyan ',
		ward: 'Kowdoor A',
		dob: '',
		dod: '',
    congregation: 'Apostalic Carmel',
		parents:'Late| Jerome Pinto, Late| Juliana Nazreth',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Sr| Mallika ',
		ward: 'Kowdoor A',
		dob: '',
		dod: '',
    congregation: 'Apostalic Carmel',
		parents:'Late| Jerome Pinto, Late| Juliana Nazreth',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Sr| Dulsis ',
		ward: 'Kowdoor B',
		dob: '',
		dod: '',
    congregation: 'Bethany',
		parents:'Late| Antony Menezes, Late| Florine DCunha',
	},
  {
		imageUrl: frAaeColaco,
		name: 'Sr| Juliana Mary ',
		ward: 'Kowdoor A',
		dob: '',
		dod: '',
 		congregation: 'Bethany',
		parents:'Late| Fredrick Rodrigues, Late| Florine Rodrigues',
  },
  {
      imageUrl: frAaeColaco,
      name: 'Sr| Reginalda',
      ward: 'Kowdoor A',
      dob: '',
      dod: '',
      congregation: 'Bethany',
      parents:'Late| Ignatius Rodrigues, Late| Monti Mary Rodrigues',
  },
  {
      imageUrl: frAaeColaco,
      name: 'Sr| Mode ',
      ward: 'Kowdoor B',
      dob: '',
      dod: '',
      congregation: 'Apostalic Carmel',
      parents:'Late| Jacky Micheal Rodrigues, Late| Seraphine Rodrigues',
  },
  {
      imageUrl: frAaeColaco,
      name: 'Sr| Maria Navitha',
      ward: 'Kowdoor A',
      dob: '',
      dod: '',
      congregation: 'Apostalic Carmel',
      parents:'Late| Hilary Vas, Mrs Benedicta DSouza',
  },
  {
      imageUrl: frAaeColaco,
      name: 'Sr| Josita',
      ward: 'Kowdoor B',
      dob: '',
      dod: '',
      congregation: 'Bethany',
      parents:'Late| Pascal Rodrigues, Late| Eliz Roseline Rodrigues',
  },
  {
      imageUrl: frAaeColaco,
      name: 'Sr| Renuka',
      ward: 'Kowdoor B',
      dob: '',
      dod: '',
      congregation: 'Apostalic Carmel',
      parents:'Late| Juliaan Lobo, Late| Apoline Lobo',
  },
  {
      imageUrl: frAaeColaco,
      name: 'Sr| Maria Sudeepa',
      ward: 'Kowdoor A',
      dob: '',
      dod: '',
      congregation: 'Apostalic Carmel',
      parents:'Mr Hilary Pinto, Late| Helen Pinto',
  },
  {
      imageUrl: frAaeColaco,
      name: 'Sr| Irene Pinto',
      ward: 'Kowdoor A',
      dob: '',
      dod: '',
      congregation: 'Selesiyan',
      parents:'Late| Ambrose Pinto, Late| Juvanna Rodrigues',
  },
  {
      imageUrl: frAaeColaco,
      name: 'Sr| Dr | Tresilla',
      ward: 'Kowdoor A',
      dob: '',
      dod: '',
      congregation: 'Bethany',
      parents:'Late| Lawrence Fredrick Pinto, Mrs Stella Lobo',
  },
  {
      imageUrl: frAaeColaco,
      name: 'Sr| Mary Jane',
      ward: 'Pompei A',
      dob: '',
      dod: '',
      congregation: 'Apostalic Carmel',
      parents:'Late| Alex Serrao, Late| Seraphina Rodrigues',
  },
  {
      imageUrl: frAaeColaco,
      name: 'Sr| Shalet Sequiera',
      ward: 'Pompei A',
      dob: '',
      dod: '',
      congregation: `Saint Ann's Providence`,
      parents:'Late| Piyad Sequiera, Late| Gertrude Pinto',
  },
  {
      imageUrl: frAaeColaco,
      name: 'Sr| Roselita',
      ward: 'Pompei B',
      dob: '',
      dod: '',
      congregation: 'Bethany',
      parents:'Late| John DSouza, Late| Angeline DSouza',
  },
  {
      imageUrl: frAaeColaco,
      name: 'Sr| Eveline Sequiera',
      ward: 'Kandar B',
      dob: '',
      dod: '',
      congregation: `Saint Ann's Providence`,
      parents:'Late| Thomas Sequiera, Late| Christine Pinto',
  },
  {
      imageUrl: frAaeColaco,
      name: 'Sr| Mary Stephen Lobo',
      ward: 'Kandar A',
      dob: '',
      dod: '',
      congregation: `Saint Ann's Providence`,
      parents:	'Late| Aanaclitus Lobo, Late| Mercine Lobo',
  },
	{
		imageUrl: frAaeColaco,
		name: 'Sr| Hildaguard',
		ward: 'Church',
		dob: '',
		dod: '',
		congregation: 'Bethany',
		parents:'Late| Felix DSouza, Late| Pauline Coelho',
	},
	{
		imageUrl: frAaeColaco,
		name: 'Sr| Mari Jane',
		ward: 'Gurpur',
		dob: '',
		dod: '',
		congregation: 'Bethany',
		parents:'Late| Baptist DSouza, Late| Sebina DSouza',
	},
	{
		imageUrl: frAaeColaco,
		name: 'Sr| Linet Preetha DSouza',
		ward: 'Addoor',
		dob: '',
		dod: '',
		congregation: 'Charity',
		parents:'Mr Plastid DSouza, Mrs Prescilla DSouza',
	},
	{
		imageUrl: frAaeColaco,
		name: 'Sr| Jacintha Rodrigues',
		ward: 'Kowdoor B',
		dob: '',
		dod: '',
		congregation: 'Bethany',
		parents:'Late| Albert Rodrigues, Late| Emiliana Rodrigues',
	},
	{
		imageUrl: frAaeColaco,
		name: 'Sr| M Francis',
		ward: 'Pompei A',
		dob: '',
		dod: '',
		congregation: 'Bethany',
		parents:'',
	},
	{
		imageUrl: frAaeColaco,
		name: 'Sr| Titus',
		ward: 'Kandar',
		dob: '',
		dod: '',
		congregation: '',
		parents:'',
	},
	{
		imageUrl: frAaeColaco,
		name: 'Sr| Allen',
		ward: 'Kowdoor B',
		dob: '',
		dod: '',
		congregation: '',
		parents:'Late| Denis DCunha, Late| Mary DCunha',
	},
	{
		imageUrl: frAaeColaco,
		name: 'Br| Cyril DSouza',
		ward: 'Gurpur',
		dob: '',
		dod: '',
		congregation: '',
		parents:'Late| Paul DSouza, Late| Coses DSouza',
	},
	{
		imageUrl: frAaeColaco,
		name: 'Rev| Fr| John Clifford Rodrigues', // Updated from Pompeichen Falkem
		ward: 'Kandar A',
		dob: '',
		dod: '',
		congregation: 'Carmelite',
		parents:'Mr Cyril Rodrigues, Mrs Leena Rodrigues',
	},
	{
		imageUrl: frAaeColaco,
		name: 'Rev| Fr| Wilson Saldanha', // Updated from Pompeichen Falkem
		ward: 'Gurpur',
		dob: '',
		dod: '',
		congregation: 'Jesuit',
		parents:'Late| Dominic Saldanha, Mrs Cynthia Saldanha',
	},
];

export { religiousVocationsEng };


