export const ROUTES = {
  PARISH_PRIEST_MESSAGE: "/parish-priest-message",
  POMPEICHEM_FALKEM: "/pompeichem-falkems",
  UPCOMING_EVENTS: "/upcoming-events",
  OBITUARIES: "/obituaries",
  EVENTS: "/events",
  ASSOCIATIONS: "/associations",
  PARISHIONERS_ACHIEVEMENTS: "/parishioners-achievements",
  POPES_INTENTION: "/popes-intentions",
  PRAYER_FOR_THE_YEAR: "/prayer-for-the-year",
  PARISH_PASTORAL_COUNCIL: "/parish-pastoral-councils",
  PARISH_PASTORAL_COUNCIL_IMAGE: "/parish-pastoral-council-image",
  ASSCIATION_OFFICE_BEARERS: "/association-office-bearer",
  PASTORAL_CORE_COMMITTEE: "/parish-pastoral-council-core-committees",
  PARISH_FINANCE_COMMITTEE: "/parish-finance-committees",
  PARISH_PRIESTS_AND_DEACONS: "/parish-priests-and-deacons",
  LANDING_PAGE_CAROUSEL: "/landing-page-carousels",
  GALLERY_IMAGES: "/gallery-images",
  PARISH_PASTORAL_21_COMMISSION: "/parish-pastoral-21-commissions",
  CONTACT: "/contact",
  WARDS: "/wards",
  PUSH_NOTIFICATIONS: "/push-notifications",
  PUSH_NOTIFICATIONS_CHECK: "/push-notifications/check",
} as const;
