export const ROUTES = {
  PARISH_PRIEST_MESSAGE: "/parish-priest-message",
  POMPEICHEM_FALKEM: "/pompeichem-falkems",
  UPCOMING_EVENTS: "/upcoming-events",
  OBITUARIES: "/obituaries",
  EVENTS: "/events",
  POPES_INTENTION: "/popes-intentions",
  PARISH_PASTORAL_COUNCIL: "/parish-pastoral-councils",
  PARISH_PASTORAL_COUNCIL_IMAGE: "/parish-pastoral-council-image",
  ASSCIATION_OFFICE_BEARERS: "/association-office-bearer",
  PASTORAL_CORE_COMMITTEE: "/parish-pastoral-council-core-committees",
  PARISH_FINANCE_COMMITTEE: "/parish-finance-committees",
  PARISH_PRIESTS_AND_DEACONS: "/parish-priests-and-deacons",
  LANDING_PAGE_CAROUSEL: "/landing-page-carousels",
  PARISH_PASTORAL_21_COMMISSION: "/parish-pastoral-21-commissions",
  SEND_REVIEW: "/send-review",
} as const;
